# -*- coding: utf-8 -*-
"""EDA_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g22KX_Upie0EN7gGxW01MSyecBYUF6dJ
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/adult (1).csv")
df
print(df)

#viewing
print(df)
print(df.head())
print(df.columns)
print(df.info())
print(df.shape)
print(df.count())
print(df.describe())

#viewing and filtering
"""
1.Select and display only the age column from the dataset.
2.Select the age, education, occupation, and income columns.
3.Display the first 10 rows using iloc.
4.Select rows 10 to 20 and display only the age and education columns.
5.Filter and display all people whose age is greater than 50.
6.Filter and display all people whose income is >50K.
7.Filter people whose age is greater than 40 and
hours-per-week is greater than 40.
8.Filter people whose education is either Bachelors
 or Masters using isin().
9.Find the mean, median, minimum, and maximum age of
 people in the dataset.
10.Find the standard deviation of age and hours-per-week.
11.Use describe() to generate the statistical summary
 of all numericalcolumns.
12.Find the number of unique values in the education column and display
 their
frequency using value_counts().
13.Find the number of people in each income category using value_counts().
15.Find the average hours-per-week of people whose income is >50K.
16.Find the average age of people whose education is Bachelors.
17.Find the youngest and oldest person in the dataset.
18.Calculate the correlation between the numerical columns using corr().
19.Find the most common value (mode) of the education and occupation column

#1
print(df['Age'].mean())
#2
print(df.shape)
#3
print(df[["Age","Education","Income"]].head(15))
#4
print(df["Workclass"].unique())
#5
print(df["Occupation"].nunique())
#6
print(df.isnull().sum())
#7
print(df["Hours per Week"].agg(['mean',"max","min","median"]))
#8
print(df["Education"].value_counts())
#9

#10
print(df[(df["Age"] >= 25) & (df["Age"] <= 40) & (df["Income"] == ">50k")])
#11
print(df[["capital loss","Capital Gain"]].agg(['mean',"max","min","median","std"]))
#12
print(df["Native Country"].value_counts().head(5))
#13
df[df["Education"].isin(["Bachelors", "Masters"])]["Hours per Week"].mean()
#14

1.Find the average age and hours-per-week separately for each income category.
2.Find the total number of rows and columns in the df DataFrame.
3.Display the first 15 rows and only the columns age, education, and income.
4.Find all unique values present in the workclass column.
5.Count how many unique values are present in the occupation column.
6.Find the number of missing values in each column.
7.Find the average, median, minimum, and maximum hours-per-week using .agg().
8.Find the number of people in each education category using value_counts().
9.Calculate the percentage of each education category using NumPy.
10.Filter people whose age is between 25 and 40 and whose income is >50K.
11.Find the minimum, maximum, mean, and standard deviation of capital-gain and capital-loss using .agg().
12.Find the top 5 most common native-country values using value_counts().
13.Find the average hours-per-week for people whose education is Bachelors or Masters.
14.Group the data by education and calculate the count, mean age, and maximum age using .groupby() and .agg().
15.Create a summary showing each income category with its count, percentage, average age,
and average hours-per-week using Pandas, NumPy, groupby(), and .agg().1.Find the average age and hours-per-week separately for each income category.
2.Find the total number of rows and columns in the df DataFrame.
3.Display the first 15 rows and only the columns age, education, and income.
4.Find all unique values present in the workclass column.
5.Count how many unique values are present in the occupation column.
6.Find the number of missing values in each column.
7.Find the average, median, minimum, and maximum hours-per-week using .agg().
8.Find the number of people in each education category using value_counts().
9.Calculate the percentage of each education category using NumPy.
10.Filter people whose age is between 25 and 40 and whose income is >50K.
11.Find the minimum, maximum, mean, and standard deviation of capital-gain and capital-loss using .agg().
12.Find the top 5 most common native-country values using value_counts().
13.Find the average hours-per-week for people whose education is Bachelors or Masters.
14.Group the data by education and calculate the count, mean age, and maximum age using .groupby() and .agg().
15.Create a summary showing each income category with its count, percentage, average age,
and average hours-per-week using Pandas, NumPy, groupby(), and .agg().

#stastical
print(df.columns)
#1
df["Age"]
#2
df[['Age','Education','Occupation','Income']]
#3
df.iloc[0:11]
#4
df[['Age','Education']].iloc[10:21]
#5
df[df["Age"]> 50]
#6
#7
df[(df["Age"]>40) & (df['Hours per Week'] >40)]
#8
df[df["Education"].isin([" Bachelors","  Masters"])]
#9
df["Age"].agg(["mean","min","max","median"])
#10
df[["Age",'Hours per Week']].std()
#11
print(df.describe())
#12
df['Education'].value_counts()
#13
df["Income"].value_counts()
#16
df[df["Education"]==" Bachelors"]["Age"].mean()
#17
df["Age"].agg(["min","max"])
#18
df[['Final Weight','Age']].corr()
#19
df[['Occupation','Education']].mode()

"""Questions
1.Identify the number of missing values present in each column of the Adult dataset.
2.Find the total number of NaN values present in the entire Adult dataset.
3.Replace all ? values in the Adult dataset with NaN using NumPy.
4.Fill missing values in the workclass column with the constant value "Unknown".
5.Fill missing values in the occupation column with the constant value "Not Available".
6.Find the mean of the age column and use it to fill its missing values.
7.Find the median of hours-per-week and use it to fill its missing values.
8.Find the mode of the workclass column and use it to fill its missing values.
9.Find the mode of the occupation column and use it to fill its missing values.
10.Delete all rows containing at least one missing value from the Adult dataset.
11.Delete rows where the occupation column contains a missing value.
12.Delete the native-country column from the Adult dataset.
13.Find the number of missing values in age, workclass, occupation, and native-country separately.
14.Fill missing values in age using mean and missing values in workclass using mode.?"""

#cleaning
#df = df.replace(" ?",None)
#1
print(df.isnull().sum())

#2
print(df.isna().sum().sum())

#3
df = df.replace("?",None)
df.isna().sum()

#4
df["Workclass"] = df["Workclass"].fillna("Unknown")
df["Workclass"].isna().sum()

#5
df["Occupation"] = df["Occupation"].fillna("Not Available")

#6
df["Age"] = df["Age"].fillna(df["Age"].mean())

import pandas as pd
#!pip install autoviz
from autoviz.AutoViz_Class import AutoViz_Class
av = AutoViz_Class()
df = pd.read_csv("/content/adult (1).csv")
av.AutoViz(
    filename="adult(1).csv",
    sep=",",
    depVar="Income",
    dfte=df
)

import pandas as pd
#!pip install sweetviz
import sweetviz as sv
df = pd.read_csv("/content/adult (1).csv")
report = sv.analyze(df)
report.show_html("chandra_report.html")

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.lineplot(data=df, x='Age', y='Capital Gain', estimator='mean', color='purple')
plt.title('Capital Gain Trend Across Age')
plt.xlabel('Age')
plt.ylabel('Mean Capital Gain')
plt.show()

df.columns

# -------------------------------
# 2. Age Distribution
# -------------------------------

sns.histplot(data=df, x="Age", bins=20, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

import pandas as pd
#!pip install dtale
import dtale

df = pd.read_csv("/content/adult (1).csv")
dtale.show(df)

!pip uninstall -y dtale

!pip uninstall -y sweetviz

!pip uninstall -y autoviz

!pip show dtale

#!pip install ydata-profiling
import pandas as pd
from ydata_profiling import ProfileReport
df = pd.read_csv("/content/adult (1).csv")
profile = ProfileReport(df,title="Adult Dataset Report")
profile.to_notebook_iframe()